spring:
  application:
    name: ebs

  profiles:
    active: ${SPRING_PROFILE:prod}


context-text: ${CONTEXT_TEXT:Zee_EBS}

server:
  port: ${SERVER_PORT:8080}

feature:
  payment:
    enabled: ${FEATURE_PAYMENT_ENABLED:false}


is:
  redis:
    Cluster: ${IS_REDIS_CLUSTER:false}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}

esb:
  name: PropsCatcher
  ip: 127.0.0.1
  port: 8056
  security:
    enabled: true
    token: dasjafdljdskjdasjfdaskfj
    roles:
    - USER
    - ADMIN
esb2:
  name: RecordPropsCatcher
  ip: 127.0.1.1
  port: 8056
  security:
    enabled: false
    token: recordcatcher
    roles:
      - USER
      - ADMIN