spring:
  application:
    name: ebs


context-text: Zee_EBS

server:
  port: 8080

feature:
  payment:
    enabled: false


is:
  redis:
    Cluster: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always